# Generated by Django 4.0.6 on 2022-07-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile1',
        ),
    ]
