# Generated by Django 4.0.6 on 2022-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_profile1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mvies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discriptions', models.CharField(max_length=20000)),
                ('image', models.ImageField(upload_to='movies/')),
                ('movie_length', models.CharField(max_length=50)),
                ('movie_director', models.CharField(max_length=40)),
                ('movie_actor', models.CharField(max_length=40)),
            ],
        ),
    ]
