# Generated by Django 4.0.6 on 2022-07-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_mvies_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='discriptions',
            field=models.TextField(max_length=20000),
        ),
    ]
