# Generated by Django 4.0.6 on 2022-07-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
